### PR TITLE
ADR for pipeline reuse

### PR DESCRIPTION
**Pull request by mikevanhemert**

### CODE REVIEW

**Review by bburky — DISMISSED** [review]
Generally agree. Design similarly structured pipelines, but don't share code _yet_. This enables fast iteration each repo while we don't yet know what code should be shared.

The one exception is to think carefully about is any place where we don’t expect any divergence at all. Like zarf install and ECR login, maybe something for S3. However, if any expected changes would require workflow yaml changes anyway or all code is one line each, there's not a lot to be gained by sharing code. If it's possible to set these up so that we can make one change and update them all later, do it, otherwise still don't focus on code reuse yet.

**Comment by belkat14** [comment]
To make sure my understanding is accurate, for the short-term to accelerate delivery, we're having folks build all of the pipelines specific to their project and the only re-use would be if they went and grabbed the code from a different project that already had it set up in these directories? 

Projects will have these top-level directories:
* `.github/actions`
* `.github/workflows`

In the future, we'll revisit the decision to buy down tech debt by setting up workflows for the 4 cases but given our current timelines that work would be more effort than return on investment in the next 3 weeks?

**Comment by mikevanhemert** [comment]
@belkat14 yes! Current path is "make all the pipelines similar / same" (copy paste where needed) and future path is set up reuse that makes sense - likely by creating the four workflows but we might pivot to something more nuanced if four common workflows doesn't satisfy the need or is over-engineered to make it work.

**Review by belkat14 — DISMISSED** [review]
Left some comments on the conversation tab. LGTM! I love ADRs so thanks for kicking it off with the first one :)

**Comment by candreacchi** [comment]
I'd like to subscribe to Drew-Notes, 10/10 recommend for the quick version to understand when you're not as pipeline savvy.  Sounds like a solid plan Mike!

**Review by blancharda — APPROVED** [review]

**Pull request merged**
